package org.example.globaledugroup.enums;


public enum TELEGRAM_STATE {
    START, OPERATORS_OF_SURVEY, RATING_OF_SURVEY, THANKS_FOR_ATTEND, FINISHED_SURVEY, SEARCH,
    START_ADMIN, ADMIN_MENU, CHOSEN_FROM, VIEWED_USERS, VIEWED_OPERATOR_DEPARTMENT,
    VIEWED_ADMIN_DEPARTMENT, VIEWED_SETTINGS_DEPARTMENT, ASK_PHONE_FOR_OPERATOR,
    ASK_FLP_FOR_OPERATOR, IS_CONFRIM_OPERATOR, ASK_CHOSEN_FOR_DELETE_OPERATOR,
    ACCEPT_SURE_OR_NOT, ASK_FLP_FOR_ADMIN, ASK_CHOSEN_FOR_DELETE_ADMIN, WROTE_TEXT_FOR_SEND, ACTIVATE_USER, ASK_CONTACT_FOR_USER, ASKED_CONTACT, IS_CONFiRM_ADMIN
}
